GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGF2aWQiLCJpYXQiOjE3MTA5MzIwMzcsImV4cCI6MTcxMDkzMjYzN30.pV7qQXkweSdimAJM7OCv7iWRMh9hVI85zdMxIEjgL_w


###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGF2aWQiLCJpYXQiOjE3MTA5MzI0Nzh9.iUOPEzF2ZaMHNdfpHomXrd8ehVH-q7klx6TWYSbO538"
    }

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGF2aWQiLCJpYXQiOjE3MTA5MzI0Nzh9.iUOPEzF2ZaMHNdfpHomXrd8ehVH-q7klx6TWYSbO538"
}

###



POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "david"
}